name: startend_app
description: "START/END投稿を軸とした進捗共有SNSアプリ"
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase - 最新バージョンに更新
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.3
  firebase_app_check: ^0.3.1
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  path: ^1.8.3
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  
  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  
  # Navigation
  go_router: ^14.6.2
  # google_mobile_ads: ^4.0.0  # 配信後に再有効化予定

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

# アプリアイコン設定
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/startend_icon.png"  # 新しいアイコン画像に変更
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/startend_icon.png"  # 新しいアイコン画像に変更
    background_color: "#ffffff"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icons/startend_icon.png"  # 新しいアイコン画像に変更
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icons/startend_icon.png" 