name: startend_app
description: "START/END投稿を軸とした進捗共有SNSアプリ"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4
  path: ^1.8.3
  path_provider: ^2.1.4
  
  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  
  # Navigation
  go_router: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 