name: startend_app
description: "START/END投稿を軸とした進捗共有SNSアプリ"
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase - 最新バージョンに更新
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_app_check: ^0.4.0
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  emoji_picker_flutter: ^3.0.0
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  path: ^1.8.3
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  crypto: ^3.0.3
  
  # オフライン対応
  connectivity_plus: ^6.0.5
  sqflite: ^2.3.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication - 最新バージョンに更新
  google_sign_in: ^7.1.1  # 最新バージョンに戻す
  sign_in_with_apple: ^7.0.1
  
  # Navigation
  go_router: ^16.0.0
  
  # URL Launcher
  url_launcher: ^6.3.2
  
  # ネイティブ広告のみ - 最新バージョンに更新
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/

# アプリアイコン設定
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/startend_icon.png"  # 新しいアイコン画像に変更
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/startend_icon.png"  # 新しいアイコン画像に変更
    background_color: "#ffffff"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icons/startend_icon.png"  # 新しいアイコン画像に変更
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icons/startend_icon.png" 