// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzqsXuEw6RlO8Eg0PXX30PaUAOoqsL6X8',
    appId: '1:201575475230:web:a14716424cb840b51fa60f',
    messagingSenderId: '201575475230',
    projectId: 'startend-sns-app',
    authDomain: 'startend-sns-app.firebaseapp.com',
    storageBucket: 'startend-sns-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpX1-HztSY1JSuhd1-VfuvKEFJBRMrXPM',
    appId: '1:201575475230:android:7d9684c6aff952801fa60f',
    messagingSenderId: '201575475230',
    projectId: 'startend-sns-app',
    storageBucket: 'startend-sns-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZZ5lv4VHRCtwf9yCO53g6lkzlQQHSCLU',
    appId: '1:201575475230:ios:fa3f7de4eb56c1131fa60f',
    messagingSenderId: '201575475230',
    projectId: 'startend-sns-app',
    storageBucket: 'startend-sns-app.firebasestorage.app',
    iosBundleId: 'com.startend.app.startendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZZ5lv4VHRCtwf9yCO53g6lkzlQQHSCLU',
    appId: '1:201575475230:ios:fa3f7de4eb56c1131fa60f',
    messagingSenderId: '201575475230',
    projectId: 'startend-sns-app',
    storageBucket: 'startend-sns-app.firebasestorage.app',
    iosBundleId: 'com.startend.app.startendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzqsXuEw6RlO8Eg0PXX30PaUAOoqsL6X8',
    appId: '1:201575475230:web:5c57fb4efc61fa5b1fa60f',
    messagingSenderId: '201575475230',
    projectId: 'startend-sns-app',
    authDomain: 'startend-sns-app.firebaseapp.com',
    storageBucket: 'startend-sns-app.firebasestorage.app',
  );
}
